### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 4Dmu** [rmcrackan/AudibleApi#22]
Hi, is downloading audiobooks supported, sorry if this is obvious but the only thing I've found related to downloading is Api.GetDownloadLicenseAsync() and that doesn't just gets a license, is there any way to download files?

**Comment by rmcrackan** [comment]
In Libation, I switched to using @Mbucari 's [AAXClean](https://github.com/Mbucari/AAXClean) for the actual download/decrypt. Around that time I removed the functional but worse code from AudibleApi. It's still in the git history:

* [Full history](https://github.com/rmcrackan/AudibleApi/commits/master/AudibleApi/Api.Download.cs)
* [Example Jun 22, 2021](https://github.com/rmcrackan/AudibleApi/blob/d8e0100032e3d69fe763c150c50f1b1f3178961c/AudibleApi/Api.Download.cs). When this was my live code, I used `DownloadAaxWorkaroundAsync` since it created a single file for both large and small books.

**Comment by 4Dmu** [comment]
thanks
