### ISSUE TITLE
AudibleApiStorage Missing ?

### ISSUE THREAD

**Issue by maurikke** [rmcrackan/AudibleApi#4]
Hello,

I had 2 questions: 
1: Is it possible that the AudibleApiStorage class is missing from the source-base? 

2: I worked around this class and created my own Locale-instance: 
   Locale oMyLocale = new Locale("test", "amazon", "uk", "co.uk", "A2I9A3Q2GNFNGQ", "en-GB");
  (i got the 'marketId' from the Python/Crystal implementation)

  With this lcoalte i pass the first logon and it get a gotcha. Also this step i can pass and then i get to the 'ApprovalNeeded approvalNeeded:'. At that moment an URL is generated like 'https://www.amazon.co.uk/ap/signin?ie=UTF8.......openid.net/auth/2.0' This request results in a 404. Can you tell me if i created the locale wrongly, or did the URLs at amazon / audible change?

I hope you can help me,
Maurice,

**Comment by rmcrackan** [comment]
Sorry, I just noticed this because for some reason github isn't sending me notifications for this project. I'm afraid I don't understand what you mean and I understand if you don't remember either 1/2 a year later.

I can connect to my uk audible account fine. Maybe this is something I already fixed so I'm going to close this. If you have more info though, we'll reopen it.
